# .streamlit/secrets.toml

server = "wav-svr-001\\capitalive"
database = "waverley"
username = "sp"
password = "1RNbrew#"
supabase_url = "https://azmblbuintwxivvbqozf.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6bWJsYnVpbnR3eGl2dmJxb3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTI4MjI1NzUsImV4cCI6MTk2ODM5ODU3NX0.p4E9K0mpVG0t71mJmC5Ar6r8HnHAG7AZYa4cQFtnHLk"
gcp_service_account = ''
public_gsheets_url = 'https://docs.google.com/spreadsheets/d/1SDOCx6Y8nXXmuojwQcur78g5W1aTRm6QU1aQ2x7S1QA/edit?usp=sharing'